[package]
name = "babylon"
version = "0.1.0"
authors = ["Jeremy Zheng <jitang.zheng@gmail.com>"]
description = "Rust implementation of reader for Babylon format."
homepage = "https://github.com/saturn-xiv/babylon"
license = "MIT"

[dependencies]
log = "0.4"
failure = "0.1"
